Rename spec device posture
diekus/screen-fold pull request #60
Opened 2021-03-04 17:03 UTC by darktears

This needs to be done in sync with a repository rename as well.

2021-03-04 17:04 UTC, darktears commented
It's for reference only, I'll rebase it when the screen fold angle removal lands.

2021-03-04 17:04 UTC, darktears commented
@anssiko @kenchris @diekus

2021-03-09 09:32 UTC, anssiko requested changes

2021-03-09 09:32 UTC, anssiko commented on index.html
> +      The Device Posture API
I'd drop "The" for consistency with the established naming conventions.

2021-03-09 09:36 UTC, anssiko commented on index.html
> +      The Device Posture API
```suggestion
      Device Posture API
```

2021-03-09 09:38 UTC, anssiko commented on index.html
> +      The Device Posture API
@darktears I fixed that for you in https://github.com/w3c/screen-fold/pull/60/commits/e9b8bfc6ba8727f969ef9e6102698c11b7f82f14

2021-03-09 09:43 UTC, anssiko commented
@xfq in order to coordinate this change, please rename this repo from "screen-fold" to "device-posture", set the redirects and merge this PR once done. (Travis CI fail seems unrelated.)

2021-03-10 03:17 UTC, merged